// src/lib/countries.ts

export const COUNTRIES = [
  // --- PRIORITÉ (Affichés en premier) ---
  { code: "PF", name: "Polynésie (Française) 🇵🇫" },
  { code: "FR", name: "France 🇫🇷" },
  { code: "NC", name: "Nouvelle Calédonie (Française) 🇳🇨" },
  { code: "WF", name: "Wallis et Futuna 🇼🇫" },
  { code: "US", name: "États Unis 🇺🇸" },
  { code: "NZ", name: "Nouvelle-Zélande 🇳🇿" },
  { code: "AU", name: "Australie 🇦🇺" },
  { code: "CA", name: "Canada 🇨🇦" },
  { code: "QU", name: "Québec (Canada) ⚜️" }, // Code spécifique AVA

  // --- LE RESTE DU MONDE (Ordre Alphabétique) ---
  { code: "AF", name: "Afghanistan" },
  { code: "ZA", name: "Afrique du sud" },
  { code: "AL", name: "Albanie" },
  { code: "DZ", name: "Algérie" },
  { code: "DE", name: "Allemagne" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AG", name: "Antigua et Barbuda" },
  { code: "AN", name: "Antilles Néerlandaises" },
  { code: "SA", name: "Arabie Saoudite" },
  { code: "AR", name: "Argentine" },
  { code: "AM", name: "Arménie" },
  { code: "AW", name: "Aruba" },
  { code: "AT", name: "Autriche" },
  { code: "AZ", name: "Azerbaïdjan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahreïn" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbade" },
  { code: "BE", name: "Belgique" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Bénin" },
  { code: "BM", name: "Bermudes" },
  { code: "BT", name: "Bhoutan" },
  { code: "BY", name: "Biélorussie" },
  { code: "MM", name: "Birmanie" },
  { code: "BO", name: "Bolivie" },
  { code: "BA", name: "Bosnie-Herzégovine" },
  { code: "BW", name: "Botswana" },
  { code: "BR", name: "Brésil" },
  { code: "BN", name: "Brunéi Darussalam" },
  { code: "BG", name: "Bulgarie" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KY", name: "Caïmans (Iles)" },
  { code: "KH", name: "Cambodge" },
  { code: "CM", name: "Cameroun" },
  { code: "CV", name: "Cap-Vert" },
  { code: "CL", name: "Chili" },
  { code: "CN", name: "Chine" },
  { code: "CX", name: "Christmas (Iles)" },
  { code: "CY", name: "Chypre" },
  { code: "CC", name: "Cocos (Iles) (Keeling)" },
  { code: "CO", name: "Colombie" },
  { code: "KM", name: "Comores" },
  { code: "CG", name: "Congo (République du)" },
  { code: "CK", name: "Cook (Iles)" },
  { code: "KP", name: "Corée du Nord" },
  { code: "KR", name: "Corée du Sud" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "HR", name: "Croatie" },
  { code: "CU", name: "Cuba" },
  { code: "DK", name: "Danemark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominique" },
  { code: "EG", name: "Egypte" },
  { code: "AE", name: "Émirats Arabes Unis" },
  { code: "EC", name: "Equateur" },
  { code: "ER", name: "Erythrée" },
  { code: "ES", name: "Espagne" },
  { code: "EE", name: "Estonie" },
  { code: "ET", name: "Ethiopie" },
  { code: "FK", name: "Falkland - Malouines (Iles)" },
  { code: "FO", name: "Féroé (Iles)" },
  { code: "FJ", name: "Fidji (Iles)" },
  { code: "FI", name: "Finlande" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambie" },
  { code: "GE", name: "Géorgie" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Grèce" },
  { code: "GD", name: "Grenade" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam (É-U)" },
  { code: "GT", name: "Guatemala" },
  { code: "GN", name: "Guinée" },
  { code: "GW", name: "Guinée Bissau" },
  { code: "GQ", name: "Guinée Équatoriale" },
  { code: "GF", name: "Guyane Française" },
  { code: "HT", name: "Haïti" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong-Kong" },
  { code: "HU", name: "Hongrie" },
  { code: "MU", name: "Île Maurice" },
  { code: "VG", name: "Îles Vierges (Britaniques)" },
  { code: "VI", name: "Iles Vierges (USA)" },
  { code: "IN", name: "Inde" },
  { code: "ID", name: "Indonésie" },
  { code: "IQ", name: "Irak" },
  { code: "IR", name: "Iran" },
  { code: "IE", name: "Irlande" },
  { code: "IS", name: "Islande" },
  { code: "IL", name: "Israël" },
  { code: "IT", name: "Italie" },
  { code: "JM", name: "Jamaïque" },
  { code: "JP", name: "Japon" },
  { code: "JO", name: "Jordanie" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KG", name: "Kirghizistan" },
  { code: "KW", name: "Koweït" },
  { code: "LA", name: "Laos" },
  { code: "LS", name: "Lesotho" },
  { code: "LV", name: "Lettonie" },
  { code: "LB", name: "Liban" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libye" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lituanie" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MG", name: "Madagascar" },
  { code: "MY", name: "Malaisie" },
  { code: "MW", name: "Malawi" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malte" },
  { code: "MA", name: "Maroc" },
  { code: "MH", name: "Marshall (Iles)" },
  { code: "MQ", name: "Martinique (Française)" },
  { code: "MR", name: "Mauritanie" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexique" },
  { code: "FM", name: "Micronésie" },
  { code: "MD", name: "Moldavie" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolie" },
  { code: "ME", name: "Monténégro" },
  { code: "MS", name: "Montserrat" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibie" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Népal" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigéria" },
  { code: "NU", name: "Niué" },
  { code: "NF", name: "Norfolk (Ile)" },
  { code: "NO", name: "Norvège" },
  { code: "OM", name: "Oman" },
  { code: "UG", name: "Ouganda" },
  { code: "UZ", name: "Ouzbékistan" },
  { code: "PK", name: "Pakistan" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée" },
  { code: "PY", name: "Paraguay" },
  { code: "NL", name: "Pays-Bas" },
  { code: "PE", name: "Pérou" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn (Iles)" },
  { code: "PL", name: "Pologne" },
  { code: "PR", name: "Porto Rico" },
  { code: "PT", name: "Portugal" },
  { code: "AD", name: "Principauté d'Andorre" },
  { code: "QA", name: "Qatar" },
  { code: "CF", name: "République Centre-Africaine" },
  { code: "CD", name: "République démocratique du Congo" },
  { code: "DO", name: "République Dominicaine" },
  { code: "AF", name: "République Islamique d'Afghanistan" },
  { code: "CZ", name: "République tchèque" },
  { code: "RE", name: "Réunion (Française)" },
  { code: "RO", name: "Roumanie" },
  { code: "GB", name: "Royaume-Uni" },
  { code: "RU", name: "Fédération de Russie" },
  { code: "RW", name: "Rwanda" },
  { code: "EH", name: "Sahara Occidental" },
  { code: "LC", name: "Sainte-Lucie" },
  { code: "SM", name: "Saint-Marin" },
  { code: "PM", name: "Saint Pierre et Miquelon" },
  { code: "VC", name: "Saint Vincent & Grenadines" },
  { code: "SB", name: "Salomon (Iles)" },
  { code: "SV", name: "Salvador" },
  { code: "WS", name: "Samoa" },
  { code: "AS", name: "Samoa américaines" },
  { code: "SN", name: "Sénégal" },
  { code: "RS", name: "Serbie" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapour" },
  { code: "SK", name: "Slovaquie" },
  { code: "SI", name: "Slovénie" },
  { code: "SO", name: "Somalie" },
  { code: "SD", name: "Soudan" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SE", name: "Suède" },
  { code: "CH", name: "Suisse" },
  { code: "SR", name: "Suriname" },
  { code: "SY", name: "Syrie" },
  { code: "TJ", name: "Tadjikistan" },
  { code: "TW", name: "Taïwan" },
  { code: "TZ", name: "Tanzanie" },
  { code: "TD", name: "Tchad" },
  { code: "TF", name: "Terres Australes Françaises" },
  { code: "TH", name: "Thaïlande" },
  { code: "TP", name: "Timor Oriental" },
  { code: "TG", name: "Togo" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinité et Tobago" },
  { code: "TN", name: "Tunisie" },
  { code: "TM", name: "Turkménistan" },
  { code: "TR", name: "Turquie" },
  { code: "TV", name: "Tuvalu" },
  { code: "UA", name: "Ukraine" },
  { code: "UY", name: "Uruguay" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Vénézuela" },
  { code: "VN", name: "Vietnam" },
  { code: "YE", name: "Yémen" },
  { code: "ZR", name: "Zaïre" },
  { code: "ZM", name: "Zambie" },
  { code: "ZW", name: "Zimbabwe" }
];
