import { Json } from "@/lib/supabase/config";
export interface AiraloPackage {
  id: string;
  airalo_id?: string;
  name: string;
  slug: string;
  day?: string;
  description?: string;
  country?: string;
  region: string;
  type: string;
  data_amount: number;
  data_unit: string;
  validity?: number;
  includes_voice?: boolean;
  includes_sms?: boolean;
  available_topup?: boolean;
  final_price_eur: number;
  final_price_usd: number;
  final_price_xpf: number;
  price_usd?: number;
  price_eur?: number;
  price_xpf?: number;
  recommended_retail_price: Json;
  operator_name?: string;
  operator_logo_url?: string;
  networks?: string | null;
  last_synced_at: string | null;
  created_at: string;
  updated_at: string | null;
  price: number;
  region_fr: string;
  currency?: string;
  title?: string;
  shortInfo?: string;
}
